/* ChordNesia / Arsip Nada Editorial: rail metadata, lirik monospace, kord brick-red, kontrol seperti tape deck. */
import { Link } from "wouter";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, CirclePlay, Gauge, Moon, Pause, Play, Search, Sun, Volume2, X } from "lucide-react";

const song = {
  title: "Mata Indahmu", artist: "ChordNesia Session", key: "C", difficulty: "Pemula", genre: "Pop akustik", tempo: 92,
  pattern: ["D", "D", "U", "U", "D", "U"],
  lines: ["[C]Kutatap dua [G]mata indahmu", "[Am]Di bawah langit [F]yang biru", "[C]Satu petikan, [G]satu cerita", "[Am]Kita nyanyikan [F]bersama", "", "[F]Tak perlu banyak [C]kata", "[G]Biarkan nada [Am]bicara", "[F]Pelan-pelan kita [C]menemukan", "[G]Rumah di dalam [C]lagu ini"],
};
const chromatic = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
const chordShapes: Record<string, string[]> = { C: ["x", "3", "2", "0", "1", "0"], G: ["3", "2", "0", "0", "0", "3"], Am: ["x", "0", "2", "2", "1", "0"], F: ["1", "3", "3", "2", "1", "1"] };
function shiftChord(chord: string, steps: number) { const match = chord.match(/^([A-G](?:#|b)?)(.*)$/); if (!match) return chord; const root = match[1].replace("Db", "C#").replace("Eb", "D#").replace("Gb", "F#").replace("Ab", "G#").replace("Bb", "A#"); const index = chromatic.indexOf(root); return index < 0 ? chord : `${chromatic[(index + steps + chromatic.length) % chromatic.length]}${match[2]}`; }

export default function SongDetail() {
  const [transpose, setTranspose] = useState(0); const [speed, setSpeed] = useState(1); const [isScrolling, setIsScrolling] = useState(false); const [isDark, setIsDark] = useState(false); const [selectedChord, setSelectedChord] = useState("C"); const [search, setSearch] = useState(""); const [showSearch, setShowSearch] = useState(false); const scrollTimer = useRef<number | null>(null);
  useEffect(() => { const handler = (event: Event) => setSelectedChord((event as CustomEvent<string>).detail); window.addEventListener("show-chord", handler); return () => window.removeEventListener("show-chord", handler); }, []);
  useEffect(() => { document.documentElement.classList.toggle("chordnesia-dark", isDark); return () => document.documentElement.classList.remove("chordnesia-dark"); }, [isDark]);
  useEffect(() => { if (scrollTimer.current) window.clearInterval(scrollTimer.current); if (isScrolling) scrollTimer.current = window.setInterval(() => window.scrollBy({ top: speed, behavior: "auto" }), 48); return () => { if (scrollTimer.current) window.clearInterval(scrollTimer.current); }; }, [isScrolling, speed]);
  const renderedLines = useMemo(() => song.lines.filter((line) => !search || line.toLowerCase().includes(search.toLowerCase())), [search]); const displayKey = shiftChord(song.key, transpose); const shape = chordShapes[selectedChord.replace(/#|b/g, "")] || ["x", "0", "2", "2", "1", "0"];
  const parseLine = (line: string) => line.split(/(\[[^\]]+\])/g).filter(Boolean).map((part, index) => { const chordMatch = part.match(/^\[([^\]]+)\]$/); if (chordMatch) { const value = shiftChord(chordMatch[1], transpose); return <button className="chord-token" key={`${value}-${index}`} onClick={() => setSelectedChord(value)}>{value}</button>; } return <span key={`${part}-${index}`}>{part}</span>; });
  return <div className="app-shell">
    <header className="site-header"><Link className="brand" href="/" aria-label="ChordNesia beranda"><img src="/manus-storage/chordnesia-mark_5da2b96b.png" alt="" className="brand-mark" /><span className="brand-word"><i>Chord</i><b>Nesia</b></span></Link><div className="header-actions"><button className="icon-button" aria-label="Cari dalam lirik" onClick={() => setShowSearch(!showSearch)}><Search size={18} /></button><button className="icon-button" aria-label="Ganti tema" onClick={() => setIsDark(!isDark)}>{isDark ? <Sun size={18} /> : <Moon size={18} />}</button><Link className="library-link" href="/">Katalog</Link></div></header>
    {showSearch && <div className="search-drawer"><Search size={17} /><input autoFocus placeholder="Cari dalam lirik..." value={search} onChange={(event) => setSearch(event.target.value)} /><button onClick={() => { setSearch(""); setShowSearch(false); }} aria-label="Tutup pencarian"><X size={17} /></button></div>}
    <main id="top" className="page-frame"><aside className="meta-rail"><Link className="back-link" href="/"><ArrowLeft size={14} /> Kembali ke katalog</Link><p className="eyebrow">LAGU / 001</p><div className="rail-rule" /><dl className="metadata"><div><dt>ARTIS</dt><dd>{song.artist}</dd></div><div><dt>GENRE</dt><dd>{song.genre}</dd></div><div><dt>KESULITAN</dt><dd><span className="level-dot" /> {song.difficulty}</dd></div><div><dt>NADA ASLI</dt><dd>{song.key} major</dd></div></dl><div className="rail-note"><Volume2 size={16} /><span>Tekan kord<br />untuk melihat bentuk.</span></div></aside>
    <section className="song-column"><div className="song-heading"><div><p className="eyebrow accent">ARSIP NADA · SESI LATIHAN</p><h1>{song.title}</h1><p className="subtitle">Sampel data awal · format kord siap dihubungkan ke CPT Lagu + ACF.</p></div><div className="heading-key"><span>KEY SEKARANG</span><strong>{displayKey}</strong></div></div><div className="strum-card"><div className="strum-label"><span>POLA GENJRENGAN</span><small>4/4 · {song.tempo} BPM</small></div><div className="strum-pattern">{song.pattern.map((stroke, index) => <span key={`${stroke}-${index}`} className={stroke === "D" ? "down" : "up"}>{stroke === "D" ? <ArrowDown size={16} /> : <ArrowUp size={16} />}<b>{stroke}</b></span>)}</div><div className="strum-count">1 &nbsp; + &nbsp; 2 &nbsp; + &nbsp; 3 &nbsp; + &nbsp; 4 &nbsp; +</div></div><div className="song-body"><div className="line-index">01<br />02<br />03<br />04<br /><br />06<br />07<br />08<br />09</div><div className="lyrics" aria-label="Lirik dan kord lagu">{renderedLines.map((line, index) => <div className={line ? "lyric-line" : "lyric-line spacer"} key={`${line}-${index}`}>{line ? parseLine(line) : ""}</div>)}</div></div><div className="sample-note"><CirclePlay size={16} /><span>Ini adalah cuplikan sampel. Tempelkan isi lagu dengan format <code>[C]Teks lirik</code> untuk menambah lagu berikutnya.</span></div></section>
    <aside className="play-rail"><div className="sticky-controls"><div className="control-block"><p className="eyebrow">TRANSPOSE</p><div className="transpose-control"><button onClick={() => setTranspose(transpose - 1)} aria-label="Turunkan nada">−</button><strong>{transpose > 0 ? `+${transpose}` : transpose}</strong><button onClick={() => setTranspose(transpose + 1)} aria-label="Naikkan nada">+</button></div><small>{displayKey} · {transpose === 0 ? "asli" : `${Math.abs(transpose)} semitone`}</small></div><div className="control-block scroll-block"><div className="control-title"><p className="eyebrow">AUTO-SCROLL</p><Gauge size={17} /></div><div className="speed-row"><button onClick={() => setSpeed(Math.max(1, speed - 1))}>−</button><span>{speed}×</span><button onClick={() => setSpeed(Math.min(4, speed + 1))}>+</button></div><button className={`scroll-button ${isScrolling ? "active" : ""}`} onClick={() => setIsScrolling(!isScrolling)}>{isScrolling ? <Pause size={16} /> : <Play size={16} />}{isScrolling ? "Jeda scroll" : "Mulai scroll"}</button></div><div className="tip-card"><span className="tip-number">01</span><p><strong>Tips sesi</strong><br />Atur kecepatan ke 1× saat pertama membaca progresi.</p></div></div></aside></main>
    {selectedChord && <div className="chord-popover"><div className="popover-top"><span>DIAGRAM KORD</span><button onClick={() => setSelectedChord("")} aria-label="Tutup diagram"><X size={15} /></button></div><strong>{selectedChord}</strong><div className="fretboard" aria-label={`Diagram kord ${selectedChord}`}>{Array.from({ length: 6 }).map((_, stringIndex) => <div className="string-line" key={stringIndex}>{Array.from({ length: 5 }).map((_, fretIndex) => <span className={fretIndex === 1 && shape[stringIndex] !== "x" && shape[stringIndex] !== "0" ? "finger" : ""} key={fretIndex}>{fretIndex === 0 ? shape[stringIndex] : ""}</span>)}</div>)}</div><small>Senar 6 → 1 · klik kord lain untuk mengganti</small></div>}
  </div>;
}
